name: Proxy Test

on: [issues]

jobs:
  proxy_test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: |
        apt-get add-apt-repository ppa:git-core/ppa
        apt-get update
        apt-get install -y git
      if: always()
    - uses: actions/checkout@v2
      if: always()
      
