name: Proxy Test

on: [issues]

jobs:
  proxy_test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: |
        cat README.md
        cd ..
        rm -rf ${{ github.workspace }}
    - run: |
        apt-get update
        apt-get install -y software-properties-common
        apt-add-repository ppa:git-core/ppa
        apt-get update
        apt-get install -y git
    - uses: actions/checkout@v2
    - run: |
        cat README.md
        cd ..
        rm -rf ${{ github.workspace }}
      
