name: Proxy Test

on:
  issues:
    types: [opened]
jobs:
  proxy_test:
    runs-on: self-hosted
    steps:
      # Checkout using REST API
      - name: Checkout using REST API
        uses: actions/checkout@v3
      - name: Verify files
        run: cat README.md

      # Checkout using Git
      - name: Install Git
        run: ./install-git.sh
      - name: Clean
        run: ./reset-workspace.sh
      - name: Checkout using Git
        uses: actions/checkout@v3
      - name: Verify files
        run: cat README.md

      # Setup Node.js
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Verify node and npm
        run: ./verify-node.sh 16

      # Cleanup
      - name: Clean
        run: ./reset-workspace.sh
