name: Proxy Test

on: [issues]

jobs:
  proxy_test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: |
        apt install -y git
      if: always()
    - uses: actions/checkout@v2
      if: always()
      
